version: 2
jobs:
  build:
    docker:
      - image: myriadeinc/node-ci:latest
        environment:
          emerald__host: emerald
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Installing dev dependencies
          command: |
            npm install
      - run:
          name: Build Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            TAG=$(git show -s --pretty=%H) make build
      - deploy:
          name: Push & deploy build
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker push myriadeinc/shadowstone:$(git show -s --pretty=%H)
            fi
